// ============================================
// CODE-DEFINED SHOP ITEMS REGISTRY
// Mirrors the theme system pattern (context/ThemeContext.js → PREMIUM_THEMES):
// items are defined here as plain JS objects and loaded into the app.
//
// This is the SOURCE OF TRUTH for item *definitions*. At runtime the DB-backed
// `ShopItem` collection is the source of truth for *state* (purchases, stock,
// soldCount, isActive). `lib/shop.js → syncCodeShopItems()` upserts these into
// the DB by `slug` (the stable key) — see that function for the sync strategy.
//
// Admin-created items remain fully editable; code items are flagged
// `source: "code"` and surfaced read-only in AdminShopManager.
// ============================================

export const CODE_SHOP_ITEMS = [
    {
        name: "Dark waves",
        slug: "dark-waves",
        description: "A shimmering dark waves profile banner.",
        category: "profile_banner",
        price: 3000,
        rarity: "mythic",
        visual: {
            icon: "Image",
            color: "#22d3ee",
            className: "",
            imageUrl:
                "https://media4.giphy.com/media/v1.Y2lkPTc5MGI3NjExZmk0eTZodDFpaWl6Zzh0dG52bjF5dGZiNTd3Y3o2OWRlYmtyOGF2ZiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/Byour3OgR0nWnRR6Tc/giphy.gif",
        },
        sortOrder: 1,
        isLimited: false,
        limitedUntil: null,
        maxStock: null,
    },
    {
        name: "Matrix Rain",
        slug: "matrix-rain",
        description: "A shimmering matrix rain profile banner.",
        category: "profile_banner",
        price: 2000,
        rarity: "mythic",
        visual: {
            icon: "Image",
            color: "#22d3ee",
            className: "",
            imageUrl:
                "https://media0.giphy.com/media/v1.Y2lkPTc5MGI3NjExZmlwNmpwdnloNHZtdTRxcDEzNnhicmFlMjRvaTZidXIxNmlpdnpjMiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/V4NSR1NG2p0KeJJyr5/giphy.gif",
        },
        sortOrder: 1,
        isLimited: false,
        limitedUntil: null,
        maxStock: null,
    },
    {
        name: "Pheonix Valorant",
        slug: "pheonix-valorant",
        description: "A shimmering pheonix valorant profile banner.",
        category: "profile_banner",
        price: 2000,
        rarity: "mythic",
        visual: {
            icon: "Image",
            color: "#22d3ee",
            className: "",
            imageUrl:
                "https://media4.giphy.com/media/v1.Y2lkPTc5MGI3NjExanBuOWhnNmZ1OW9zZGtlOGRqejRmaDRzaWh5bmZnb2d6anpiejA5YiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/Uwfp8HJKRL9kpjjPmU/giphy.gif",
        },
        sortOrder: 1,
        isLimited: false,
        limitedUntil: null,
        maxStock: null,
    },
    {
        name: "Valorant Esports Knife",
        slug: "valorant-esports-knife",
        description: "A shimmering valorant esports knife profile banner.",
        category: "profile_banner",
        price: 2000,
        rarity: "mythic",
        visual: {
            icon: "Image",
            color: "#22d3ee",
            className: "",
            imageUrl:
                "https://media2.giphy.com/media/v1.Y2lkPTc5MGI3NjExMzlpODlnaHlscHlib2Eya3ltbDB2aTcyeTV0NzQ2ZmtjMGpmbmUwYyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/IEhxHAKBN6XfoiKQbT/giphy.gif",
        },
        sortOrder: 1,
        isLimited: false,
        limitedUntil: null,
        maxStock: null,
    },
    {
        name: "Valorant Chamber",
        slug: "valorant-chamber",
        description: "A shimmering valorant chamber profile banner.",
        category: "profile_banner",
        price: 2000,
        rarity: "mythic",
        visual: {
            icon: "Image",
            color: "#22d3ee",
            className: "",
            imageUrl:
                "https://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExZWt5ZjBvNmJzbHM0bTdiazhkNGZvMGVlaWw1c2ZwZjVkYm8wcHEydCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/m3N5PpxSyYyFICeSvb/giphy.gif",
        },
        sortOrder: 1,
        isLimited: false,
        limitedUntil: null,
        maxStock: null,
    },
    {
        name: "Space waves",
        slug: "space-waves",
        description: "A shimmering space waves profile banner.",
        category: "profile_banner",
        price: 900,
        rarity: "legendary",
        visual: {
            icon: "Image",
            color: "#22d3ee",
            className: "",
            imageUrl:
                "https://media2.giphy.com/media/v1.Y2lkPTc5MGI3NjExOXh0NXd0NHhycjJ6b212dmYyZnRqdjRnbWZwcjNva2t3MHhjcXR4ZyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/Fbox1ygIqnga5dLinz/giphy.gif",
        },
        sortOrder: 1,
        isLimited: false,
        limitedUntil: null,
        maxStock: null,
    },
    {
        name: "Goku",
        slug: "goku",
        description: "A shimmering goku profile banner.",
        category: "profile_banner",
        price: 1200,
        rarity: "mythic",
        visual: {
            icon: "Image",
            color: "#22d3ee",
            className: "",
            imageUrl:
                "https://media0.giphy.com/media/v1.Y2lkPTc5MGI3NjExcmZxbmN6cmhrcWZkbmplZTN2aHNxNmRqNzg0a2U3aW94bG1tZGFmayZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/osm7o1nCvv7pR7AyGO/giphy.gif",
        },
        sortOrder: 1,
        isLimited: false,
        limitedUntil: null,
        maxStock: null,
    },
    {
        name: "Retro Car",
        slug: "retro-car",
        description: "A shimmering loop retro car profile banner.",
        category: "profile_banner",
        price: 600,
        rarity: "epic",
        visual: {
            icon: "Image",
            color: "#22d3ee",
            className: "",
            imageUrl:
                "https://media2.giphy.com/media/v1.Y2lkPTc5MGI3NjExYm0yMTh1YWQxZzBlN3U3Yzg1dTJza2MwbXJocDFnbDRwaGFtNTEyOSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/GGqwHutw9TpT9xOIfW/giphy.gif",
        },
        sortOrder: 1,
        isLimited: false,
        limitedUntil: null,
        maxStock: null,
    },
    {
        name: "Minecraft Frog",
        slug: "minecraft-frog",
        description: "A looping minecraft frog profile banner.",
        category: "profile_banner",
        price: 500,
        rarity: "epic",
        visual: {
            icon: "Image",
            color: "#22d3ee",
            className: "",
            imageUrl:
                "https://media0.giphy.com/media/v1.Y2lkPTc5MGI3NjExaGp3eDQzazJjdDM0MzF6M2tleDVkYjZvd2lkYjY3ZjJuNHNjaHp6ayZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/r8GMmlV8qGrfZ3txfX/giphy.gif",
        },
        sortOrder: 1,
        isLimited: false,
        limitedUntil: null,
        maxStock: null,
    },
    {
        name: "Valorant Astra",
        slug: "valorant-astra",
        description: "A looping astra profile banner.",
        category: "profile_banner",
        price: 5000,
        rarity: "mythic",
        visual: {
            icon: "Image",
            color: "#22d3ee",
            className: "",
            imageUrl:
                "https://media3.giphy.com/media/v1.Y2lkPTc5MGI3NjExNHEwY2k5Mm9xYWJoZGIweGVhNDAyMmU1Y3dkdThwMTZ5cWoxM3hxMCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/xvRPIAtMwKQ2SlxKtx/giphy.gif",
        },
        sortOrder: 1,
        isLimited: false,
        limitedUntil: null,
        maxStock: null,
    },
    {
        name: "Valorant Chess",
        slug: "valorant-chess",
        description: "A looping chess profile banner.",
        category: "profile_banner",
        price: 200,
        rarity: "rare",
        visual: {
            icon: "Image",
            color: "#22d3ee",
            className: "",
            imageUrl:
                "https://media4.giphy.com/media/v1.Y2lkPTc5MGI3NjExOXphYzJrdzczM3Qza3NoYWQ0YjNjeXVmcmQ2dmlmeTY0MWxka2Z6dyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/zJsbaFbk5NSz2PlqmE/giphy.gif",
        },
        sortOrder: 1,
        isLimited: false,
        limitedUntil: null,
        maxStock: null,
    },
    {
        name: "Cosmic Wave Dance",
        slug: "cosmic-wave-dance",
        description: "A looping dance profile banner.",
        category: "profile_banner",
        price: 4500,
        rarity: "legendary",
        visual: {
            icon: "Image",
            color: "#22d3ee",
            className: "",
            imageUrl:
                "https://media4.giphy.com/media/v1.Y2lkPTc5MGI3NjExbmM1cTV6Y3hwZG1ncTN4eXJubnk4ZDRzcHF0dG4zcHZ6a2Q4ODdzciZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/njZPp4pQ0g4fe/giphy.gif",
        },
        sortOrder: 1,
        isLimited: false,
        limitedUntil: null,
        maxStock: null,
    },
    {
        name: "Cosmic Shri Vishnu",
        slug: "cosmic-shri-vishnu",
        description: "A looping shri Vishnu profile banner.",
        category: "profile_banner",
        price: 6000,
        rarity: "mythic",
        visual: {
            icon: "Image",
            color: "#22d3ee",
            className: "",
            imageUrl:
                "https://media3.giphy.com/media/v1.Y2lkPTc5MGI3NjExdGhham1pb3p4eGs4anp5MXp6NWQwOTVrOHFiaXNtcGdkbDJvc2hkNyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/axDCfXOjALXfoxDryF/giphy.gif",
        },
        sortOrder: 1,
        isLimited: false,
        limitedUntil: null,
        maxStock: null,
    },
    {
        name: "Square dark art",
        slug: "square-dark-art",
        description: "A looping square dark art profile banner.",
        category: "profile_banner",
        price: 120,
        rarity: "common",
        visual: {
            icon: "Image",
            color: "#22d3ee",
            className: "",
            imageUrl:
                "https://media2.giphy.com/media/v1.Y2lkPTc5MGI3NjExeWN5eHR2b2JmZjB6ZjJyMmJta3FhdjFrczRvNWVvYm8wanRjcGM3dCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/xTiTnI8sdOkGMKzL44/giphy.gif",
        },
        sortOrder: 1,
        isLimited: false,
        limitedUntil: null,
        maxStock: null,
    },
    {
        name: "Loop Geometry",
        slug: "loop-geometry",
        description: "A looping loop geometry profile banner.",
        category: "profile_banner",
        price: 120,
        rarity: "common",
        visual: {
            icon: "Image",
            color: "#22d3ee",
            className: "",
            imageUrl:
                "https://media2.giphy.com/media/v1.Y2lkPTc5MGI3NjExOGNhMzZjOWhkemFveG9zZmJsZXkwN2lwY3pyNXRxdjF3dHlnaGNuaCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/MS6EUbcUsOC6AYRbYf/giphy.gif",
        },
        sortOrder: 1,
        isLimited: false,
        limitedUntil: null,
        maxStock: null,
    },
    {
        name: "Pac man",
        slug: "pac-man",
        description: "A looping pac man profile banner.",
        category: "profile_banner",
        price: 300,
        rarity: "common",
        visual: {
            icon: "Image",
            color: "#22d3ee",
            className: "",
            imageUrl:
                "https://media2.giphy.com/media/v1.Y2lkPTc5MGI3NjExMjZkdHdheGF3eXhranN2dGl0b3BqaXp2YXQwbmlvcGp1cXZkd28zcCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/hkqefnFjn2MWVl6xvq/giphy.gif",
        },
        sortOrder: 1,
        isLimited: false,
        limitedUntil: null,
        maxStock: null,
    },
    {
        name: "Cozy night",
        slug: "cozy-night",
        description: "A looping cozy night profile banner.",
        category: "profile_banner",
        price: 900,
        rarity: "epic",
        visual: {
            icon: "Image",
            color: "#22d3ee",
            className: "",
            imageUrl:
                "https://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExdTFwY2duNmszOWdhM2ppN3JseXFwYnpxZnY4NWhlMHJxaTg1bjVtaiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/Basrh159dGwKY/giphy.gif",
        },
        sortOrder: 1,
        isLimited: false,
        limitedUntil: null,
        maxStock: null,
    },

    // ━━━ Chat Bubble Themes ━━━
    {
        name: "Neon Glow",
        slug: "neon-glow",
        description: "A neon green glow effect for your chat bubbles.",
        category: "chat_bubble",
        price: 300,
        rarity: "rare",
        visual: {
            icon: "MessageCircle",
            color: "#22c55e",
            className: "",
        },
        sortOrder: 50,
        isLimited: false,
        limitedUntil: null,
        maxStock: null,
    },
    {
        name: "Frosted Glass",
        slug: "frosted-glass",
        description: "A frosted glass effect for your chat bubbles.",
        category: "chat_bubble",
        price: 400,
        rarity: "epic",
        visual: {
            icon: "MessageCircle",
            color: "#94a3b8",
            className: "",
        },
        sortOrder: 51,
        isLimited: false,
        limitedUntil: null,
        maxStock: null,
    },
    {
        name: "Sunset Fire",
        slug: "sunset-fire",
        description: "A warm sunset fire gradient for your chat bubbles.",
        category: "chat_bubble",
        price: 500,
        rarity: "legendary",
        visual: {
            icon: "MessageCircle",
            color: "#f97316",
            className: "",
        },
        sortOrder: 52,
        isLimited: false,
        limitedUntil: null,
        maxStock: null,
    },
    {
        name: "Ocean Depth",
        slug: "ocean-depth",
        description: "A deep ocean blue gradient for your chat bubbles.",
        category: "chat_bubble",
        price: 400,
        rarity: "epic",
        visual: {
            icon: "MessageCircle",
            color: "#0891b2",
            className: "",
        },
        sortOrder: 53,
        isLimited: false,
        limitedUntil: null,
        maxStock: null,
    },
    {
        name: "Matrix Rain",
        slug: "matrix-rain",
        description: "A matrix-style green code rain effect for your bubbles.",
        category: "chat_bubble",
        price: 500,
        rarity: "mythic",
        visual: {
            icon: "MessageCircle",
            color: "#22c55e",
            className: "",
        },
        sortOrder: 54,
        isLimited: false,
        limitedUntil: null,
        maxStock: null,
    },
    {
        name: "Cyber Punk",
        slug: "cyber-punk",
        description: "A cyberpunk neon glow for your chat bubbles.",
        category: "chat_bubble",
        price: 500,
        rarity: "legendary",
        visual: {
            icon: "MessageCircle",
            color: "#d946ef",
            className: "",
        },
        sortOrder: 57,
        isLimited: false,
        limitedUntil: null,
        maxStock: null,
    },
    {
        name: "Circuit Trace",
        slug: "circuit-trace",
        description: "Glowing circuit lines trace the edge of every message you send.",
        category: "chat_bubble",
        price: 300,
        rarity: "rare",
        visual: {
            icon: "MessageCircle",
            color: "#06b6d4",
            className: "",
        },
        sortOrder: 58,
        isLimited: false,
        limitedUntil: null,
        maxStock: null,
    },
    {
        name: "Hatch Lines",
        slug: "hatch-lines",
        description: "A quiet crosshatch texture for a low-key bubble.",
        category: "chat_bubble",
        price: 100,
        rarity: "common",
        visual: {
            icon: "MessageCircle",
            color: "#a1a1aa",
            className: "",
        },
        sortOrder: 61,
        isLimited: false,
        limitedUntil: null,
        maxStock: null,
    },
    {
        name: "Terrain Waves",
        slug: "terrain-waves",
        description: "Concentric ripples across every message you send.",
        category: "chat_bubble",
        price: 175,
        rarity: "uncommon",
        visual: {
            icon: "MessageCircle",
            color: "#2dd4bf",
            className: "",
        },
        sortOrder: 62,
        isLimited: false,
        limitedUntil: null,
        maxStock: null,
    },
    {
        name: "Starburst",
        slug: "starburst",
        description: "Radiating lines burst outward from the corner of your bubble.",
        category: "chat_bubble",
        price: 300,
        rarity: "rare",
        visual: {
            icon: "Sparkles",
            color: "#a78bfa",
            className: "",
        },
        sortOrder: 63,
        isLimited: false,
        limitedUntil: null,
        maxStock: null,
    },
    {
        name: "Hex Frame",
        slug: "hex-frame",
        description: "A honeycomb weave with a slow-pulsing amber border.",
        category: "chat_bubble",
        price: 300,
        rarity: "rare",
        visual: {
            icon: "Sparkles",
            color: "#f59e0b",
            className: "",
        },
        sortOrder: 64,
        isLimited: false,
        limitedUntil: null,
        maxStock: null,
    },
    {
        name: "Prism Fracture",
        slug: "prism-fracture",
        description: "Shattered crystal lines with an animated glowing edge.",
        category: "chat_bubble",
        price: 500,
        rarity: "legendary",
        visual: {
            icon: "Sparkles",
            color: "#ec4899",
            className: "",
        },
        sortOrder: 65,
        isLimited: false,
        limitedUntil: null,
        maxStock: null,
    },
];
